editors/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^update-rating/$', 'editors.views.update_editor_rating', name='update_editor_rating'),
    url(r'^create/step1/$', 'editors.views.create_editor_step1', name='create_editor_step1'),
    url(r'^create/step2/$', 'editors.views.create_editor_step2', name='create_editor_step2'),
    url(r'^create-test/$', 'editors.views.create_test', name='create_test'),
    url(r'^test/(?P<test_id>[0-9]+)/$', 'editors.views.start_test', name='start_test'),
    url(r'^skip/(?P<question_id>[0-9]+)/(?P<test_id>[0-9]+)/$', 'editors.views.skip_question', name='skip_question'),
    url(r'^test-completed/(?P<test_id>[0-9]+)/$', 'editors.views.test_completed', name='test_completed'),
    url(r'^create/step3/$', 'editors.views.create_editor_step3', name='create_editor_step3'),
    url(r'^create/step4/$', 'editors.views.create_editor_step4', name='create_editor_step4'),
    url(r'^get-qualification-form/$', 'editors.views.get_qualification_form', name='get_qualification_form'),
    url(r'^get-experience-form/$', 'editors.views.get_experience_form', name='get_experience_form'),
    url(r'^save-qualification-form/$', 'editors.views.save_qualification_form', name='save_qualification_form'),
    url(r'^save-experience-form/$', 'editors.views.save_experience_form', name='save_experience_form'),
    url(r'^edit-qualification-form/(?P<qualification_id>[0-9]+)/$', 'editors.views.edit_qualification_form', name='edit_qualification_form'),
    url(r'^edit-experience-form/(?P<experience_id>[0-9]+)/$', 'editors.views.edit_experience_form', name='edit_experience_form'),
    url(r'^delete-qualification/$', 'editors.views.delete_qualification', name='delete_qualification'),
    url(r'^delete-experience/$', 'editors.views.delete_experience', name='delete_experience'),
    url(r'^show-qualification/$', 'editors.views.show_qualification', name='show_qualification'),
    url(r'^show-experience/$', 'editors.views.show_experience', name='show_experience'),
    url(r'^get-research-interest/$', 'editors.views.get_research_interest', name='get_research_interest'),
    url(r'^quote-request/$', 'editors.views.quote_request', name='quote_request'),
    url(r'^paper-request/$', 'editors.views.paper_request', name='paper_request'),
    url(r'^edit-profile/$', 'editors.views.edit_editor', name='edit_editor'),
    url(r'^delete-file/$', 'editors.views.delete_file', name='delete_file'),
    url(r'^delete-qualification-file/$', 'editors.views.delete_qualification_file', name='delete_qualification_file'),
    url(r'^paper-reject/(?P<paper_id>[0-9]+)/update-status/$', 'editors.views.reject_request', name='reject_request'),
    url(r'^paper/(?P<paper_id>[0-9]+)/update-status/$', 'editors.views.update_paper_status', name='update_paper_status'),
    url(r'^paper/ready/$', 'editors.views.paper_ready', name='paper_ready'),
    url(r'^add-to-cart/$', 'editors.views.add_to_cart', name='add_to_cart'),
    url(r'^raw-paper/download/(?P<paper_id>[0-9]+)/$', 'editors.views.raw_paper_download', name='raw_paper_download'),
    url(r'^paper/download/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_download', name='paper_download'),
    url(r'^paper/approved/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_approved', name='paper_approved'),
    url(r'^paper/complete/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_complete', name='paper_complete'),
    url(r'^rating/$', 'editors.views.rating', name='rating'),
    url(r'^delete-rating/$', 'editors.views.delete_rating', name='delete_rating'),
    url(r'^settings/$', 'editors.views.account_settings', name='settings'),
    url(r'^add-card/$', 'editors.views.add_card', name='add_card'),
    url(r'^make-primary/(?P<payment_method_id>[\w-]+)/$', 'editors.views.make_primary', name='make_primary'),
    url(r'^delete-card/(?P<payment_method_id>[\w-]+)/$', 'editors.views.delete_card', name='delete_card'),
    url(r'^get-paid/$', 'editors.views.get_paid', name='get_paid'),
    url(r'^stripe/connect/$', 'editors.stripe_connect.stripe_connect', name='stripe_connect'),
    url(r'^stripe/authenticated/$', 'editors.stripe_connect.stripe_authenticated', name='stripe_authenticated'),
    url(r'^(?P<username>\w+)/$', 'editors.views.profile', name='profile'),
]

eseditor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home Url
    url(r'^$', 'editors.views.editing_services', name='editing_services'),
    url(r'^about-us/$', 'accounts.views.about_us', name='about_us'),
    url(r'^contact-us/$', 'accounts.views.contact_us', name='contact_us'),
    url(r'^newsletter/$', 'accounts.views.newsletter', name='newsletter'),

    url(r'^editors/$', 'editors.views.editor_home', name='home'),
    url(r'^load_more_editors/$', 'editors.views.load_more_editors', name='load_more_editors'),
    url(r'^load-more-edited-paper/$', 'editors.views.load_more_edited_paper', name='load_more_edited_paper'),
    url(r'^load-more-paper-request/$', 'editors.views.load_more_paper_request', name='load_more_paper_request'),
    url(r'^load-more-quotes-request/$', 'editors.views.load_more_quotes_request', name='load_more_quotes_request'),
    url(r'^load-more-fiancial-activites/$', 'editors.views.load_more_fiancial_activities', name='load_more_fiancial_activities'),
    url(r'^job-page/paper/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_detail', name='paper_detail'),

    # App Url
    url(r'editors/', include('editors.urls')),
    url(r'student/', include('students.urls')),
    url(r'accounts/', include('accounts.urls')),
    url(r'messages/', include('message.urls')),

    # Logout Url
    url(r'^logout/$', views.logout, {'next_page': settings.LOGIN_URL}, name="logout"),

    # Reset Password Url
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
         name='password_reset_done'),

    # Rating URLs
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),

    # checkout Url
    url(r'^checkout/$', 'editors.views.checkout', name='checkout'),

    # Media Url
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT})
]

students/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^edit/$', 'students.views.edit_student', name='edit_student'),
    url(r'^settings/$', 'students.views.student_settings', name='student_settings'),
    url(r'^(?P<username>\w+)/$', 'students.views.student_profile', name='student_profile'),
    url(r'^open-paper-modal/$', 'students.views.openmodal', name='openmodal'),
    url(r'^load-more-paper/$', 'students.views.load_more_paper', name='load_more_paper'),
    url(r'^load-more-quotes/$', 'students.views.load_more_quotes', name='load_more_quotes'),
    url(r'^load-more-activities/$', 'students.views.load_more_activities', name='load_more_activities'),

]

editors/forms.py
from __future__ import unicode_literals
from datetime import datetime
import re

from django import forms
from django.conf import settings
from django.forms import FileInput
from django_countries import countries
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from editors.models import MONTH_CHOICES, RESEARCH_METHOD_CHOICES, REFERENCING_CHOICES, DEGREE_LEVEL_CHOICES
from editors.utils import get_year_drop_down
from editors.models import Editors, PaperRequest, EXP_YEAR, EXP_MONTH, Discipline, Answer, TestQuestion


class EditorFormStep1(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}))
    phone_no = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm', 'maxlength': '15'}))
    research_methods = forms.CharField(widget=forms.Select(choices=RESEARCH_METHOD_CHOICES, attrs={'class': 'form-control input-sm'}))
    referencing_style = forms.CharField(widget=forms.Select(choices=REFERENCING_CHOICES, attrs={'class': 'form-control input-sm'}))
    optional_research_methods = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=False)
    optional_referencing_style = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=False)
    discipline = forms.MultipleChoiceField(widget=forms.Select(attrs={'class': 'form-control input-xs', 'multiple': 'multiple'}))
    research_interest = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=False)
    avatar = forms.ImageField(required=False)
    identity_document = forms.FileField(required=False)
    address_document = forms.FileField(required=False)
    qualification_document = forms.FileField(required=False)
    street1 = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=True)
    street2 =forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=False)
    city  = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=True)
    state = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=True)
    postal_code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=False)
    country = forms.CharField(widget=forms.Select(choices=countries, attrs={'class': 'form-control input-sm'}), required=True)
    nationality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}), required=False)
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control input-sm', 'cols': '0', 'rows': '0'}), required=False)
    default_avatar = forms.CharField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(EditorFormStep1, self).__init__(*args, **kwargs)
        self.fields['discipline'] = forms.MultipleChoiceField(
            choices=[(discipline.id, str(discipline.name)) for discipline in Discipline.objects.all()]
        )
        self.fields['discipline'].required = True
        

    def clean_email(self):
        try:
            existing_user = User.objects.get(email__iexact=self.cleaned_data['email'])
            if existing_user:
                self._errors["email"] = self.error_class(["An account already exists under this email address. Please use the forgot password function to log in."])
        except User.MultipleObjectsReturned:
            self._errors["email"] = self.error_class(["An account already exists under this email address. Please use the forgot password function to log in."])
        except:
            pass

        return self.cleaned_data['email']
        

    def clean_optional_research_methods(self):
        research_methods = self.cleaned_data.get('research_methods')
        optional_research_methods = self.cleaned_data.get("optional_research_methods", "")

        if research_methods == "Others":
            if not optional_research_methods:
                raise forms.ValidationError('This field is required.')

        return optional_research_methods

    def clean_optional_referencing_style(self):
        referencing_style = self.cleaned_data.get('referencing_style')
        optional_referencing_style = self.cleaned_data.get("optional_referencing_style", "")

        if referencing_style == "Others":
            if not optional_referencing_style:
                raise forms.ValidationError('This field is required.')

        return optional_referencing_style


class TestForm(forms.Form):
    question_id = forms.CharField(widget=forms.HiddenInput())
    answer = forms.ModelChoiceField(queryset=Answer.objects.all(), widget=forms.RadioSelect())

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question', None)
        super(TestForm, self).__init__(*args, **kwargs)
        self.fields['answer'].queryset = Answer.objects.filter(question=question)
        self.fields['answer'].empty_label = None
        

class QualificationForm(forms.Form):
    degree = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}))
    university = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}))
    from_month = forms.CharField(widget=forms.Select(choices=MONTH_CHOICES, attrs={'class': 'form-control input-sm'}))
    from_year = forms.CharField(widget=forms.Select(choices=get_year_drop_down(), attrs={'class': 'form-control input-sm'}))
    to_month = forms.CharField(widget=forms.Select(choices=MONTH_CHOICES, attrs={'class': 'form-control input-sm'}))
    to_year = forms.CharField(widget=forms.Select(choices=get_year_drop_down(), attrs={'class': 'form-control input-sm'}))
    degree_level = forms.CharField(widget=forms.Select(choices=DEGREE_LEVEL_CHOICES, attrs={'class': 'form-control input-sm'}))
    qualification_document = forms.FileField(required=False)


class ExperienceForm(forms.Form):
    company_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}))
    location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'cols': '0', 'rows': '0' }))
    is_current = forms.BooleanField(required=False)
    from_month = forms.CharField(widget=forms.Select(choices=MONTH_CHOICES, attrs={'class': 'form-control input-sm'}))
    from_year = forms.CharField(widget=forms.Select(choices=get_year_drop_down(), attrs={'class': 'form-control input-sm'}))
    to_month = forms.CharField(widget=forms.Select(choices=MONTH_CHOICES, attrs={'class': 'form-control input-sm'}))
    to_year = forms.CharField(widget=forms.Select(choices=get_year_drop_down(), attrs={'class': 'form-control input-sm'}))


class QuoteForm(forms.Form):
    editor_id = forms.CharField(widget=forms.HiddenInput())
    discipline = forms.CharField(widget=forms.Select(attrs={'class': 'form-control multiselect input-sm myinputclass', 'required': 'required'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder': 'Title of the Paper', 'maxlength': '100'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control input-sm myinputclass', 'rows': 5, 'placeholder': 'Description of the Paper', 'maxlength': '1000'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder': 'First Name', 'maxlength': '30'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder': 'Last Name', 'maxlength': '30'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder': 'Email', 'maxlength': '75'}))
    words_count = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder': 'Words count of the paper', 'maxlength': '10'}))
    document = forms.FileField(required=False)


class ShortQuoteForm(forms.Form):
    editor_id = forms.CharField(widget=forms.HiddenInput())
    discipline = forms.CharField(widget=forms.Select(attrs={'class': 'form-control multiselect input-sm myinputclass', 'required': 'required'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder': 'Title of the Paper', 'maxlength': '100'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control input-sm myinputclass', 'rows': 5, 'placeholder': 'Description of the Paper', 'maxlength': '1000'}))
    words_count = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder': 'Words count of the paper', 'maxlength': '10'}))
    document = forms.FileField(required=False)


class PaperForm(forms.Form):
    editor_id = forms.CharField(widget=forms.HiddenInput())
    discipline = forms.CharField(widget=forms.Select(attrs={'class': 'form-control multiselect input-sm myinputclass', 'required': 'required'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder' : 'Title of the Paper', 'maxlength': '100'}))
    price = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control input-sm myinputclass', 'placeholder': 'Price (%s)' % settings.PLATFORM_CURRENCY_DISPLAY}))

templates/students/load_more_activities.html
{% load staticfiles %}
{% load stars %}

{% for activity in activities %}
<tr>
    <td>
    <a href="{% url 'paper_detail' activity.paper.id %}" style="text-decoration: none; color: #b80924;">{{ activity.paper.title|title }}</strong></a></td>
    <td>{{ activity.created|date:"M d, Y" }}</td>
        <td class="col-md-3"> <a style="text-decoration: none;" href="{% url 'profile' activity.paper.editor.user.username %}">
        {{ activity.paper.editor.user.get_full_name }}</a></td>
        
    <td>
        <span class="tag label label-danger">{{ activity.type }}</span>
    </td>
    <td>{{ currency }} {{ activity.get_dollar_amount|floatformat:"2" }}</td>
</tr>
{% endfor %}

templates/students/load_more_paper.html
{% load staticfiles %}
{% load stars %}

{% for paper in papers %}
    <tr>
        <td>{{ forloop.counter|get_serial_no:start }}</td>
        <td>
        <a href="{% url 'paper_detail' paper.id %}" style="text-decoration: none; color: #b80924;">{{ paper.title|title }}</a></td>
        <td>{{ paper.created|date:"M d, Y" }}</td>
        <td>{{ currency }} {{ paper.price_paid|floatformat:"2" }}</td>
        <td>{{ paper.status }}</td>
    </tr>
{% endfor %}

templates/students/load_more_quotes.html
{% load staticfiles %}
{% load stars %}

{% for quote in quotes %}
<tr>
    <td>{{ forloop.counter|get_serial_no:start }}</td>
    <td>{{ quote.title }}</td>
    <td><span class="tag label label-warning">{{ quote.discipline.name }}</span></td>
    <td><a style="text-decoration:none;" href="{% url 'profile' quote.editor.user.username %}">{{ quote.editor.user.get_full_name }}</a></td>
    <td>
        <p title="Description" data-toggle="popover" data-trigger="hover" data-placement="top" data-content="{{ quote.description }}" style="cursor: pointer; color: #b80924;">{{ quote.description|truncatechars:10 }}</p>
    </td>
    <td>{{ quote.created|date:"M d, Y" }}</td>
</tr>
{% endfor %}

templates/students/paper_form.html
{% load staticfiles %}
<div class="modal fade" id="id_paper_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="new_modal">
            <div class="modal-overlay" id="id_paper_overlay">
                <img src="{% static 'images/spin.svg' %}"/>
            </div>
            <form id="id_paper_form" class="form-horizontal" action="{% url 'paper_request' %}" method="post" onsubmit="return paper_request($(this))" enctype="multipart/form-data" style="color: black;">
                {% csrf_token %}
                {{ paper_form.editor_id }}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Submit a paper</h4>
                </div>
                <div class="modal-body">
                    <div class="row paddingtop-20">
                        <div class="col-md-12">
                            <div class="form-group" id="id_title_error_parent_div">
                                <label for="Title" class="control-label col-md-2">Title</label>
                                <div class="col-md-10">
                                    {{ paper_form.title }}
                                    <small id="id_title_error" class="es-error"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row paddingtop-20">
                        <div class="col-md-12">
                            <div class="form-group" id="id_discipline_error_parent_div">
                                <label for="discipline" class="control-label col-md-2">Disciplines</label>
                                <div class="col-md-10">
                                    <select class="form-control" name="discipline" id="id_discipline">
                                        <option value="" selected="">Select Discipline</option>
                                        {% for discipline in editor.discipline.all %}
                                            <option value="{{ discipline.name }}">{{ discipline.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <small id="id_discipline_error" class="es-error"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row paddingtop-20">
                        <div class="col-md-12">
                            <div class="form-group" id="id_price_error_parent_div">
                                <label for="price" class="control-label col-md-2">Price</label>
                                <div class="col-md-10">
                                    {{ paper_form.price }}
                                    <small id="id_price_error" class="es-error"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row paddingtop-20">
                        <div class="col-md-12">
                            <div class="form-group" id="id_description_error_parent_div">
                                <label for="description" class="control-label col-md-2">Description</label>
                                <div class="col-md-10">
                                    {{ paper_form.description }}
                                    <small id="id_description_error" class="es-error"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% if not role == 'student' %}
                        <div class="row paddingtop-20">
                            <div class="col-md-12">
                                <div class="form-group" id="id_first_name_error_parent_div">
                                    <label for="name" class="control-label col-md-2">First Name</label>
                                    <div class="col-md-10">
                                        {{ paper_form.first_name }}
                                        <small id="id_first_name_error" class="es-error"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row paddingtop-20">
                            <div class="col-md-12">
                                <div class="form-group" id="id_last_name_error_parent_div">
                                    <label for="name" class="control-label col-md-2">Last Name</label>
                                    <div class="col-md-10">
                                        {{ paper_form.last_name }}
                                        <small id="id_last_name_error" class="es-error"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row paddingtop-20">
                            <div class="col-md-12">
                                <div class="form-group" id="id_email_error_parent_div">
                                    <label for="email" class="control-label col-md-2">Email</label>
                                    <div class="col-md-10">
                                        {{ paper_form.email }}
                                        <small id="id_email_error" class="es-error"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    <div class="row paddingtop-20">
                        <div class="col-md-12">
                            <div class="form-group" id="id_words_count_error_parent_div">
                                <label for="words_count" class="control-label col-md-2">Words Count</label>
                                <div class="col-md-10">
                                    {{ paper_form.words_count }}
                                    <small id="id_words_count_error" class="es-error"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row paddingtop-20" style="margin-top: -10px;">
                        <div class="col-md-12">
                            <div class="form-group" id="id_paper_error_parent_div">
                                <label for="paper" class="control-label col-md-2">Paper</label>
                                <div class="col-md-10 paddingtop-20">
                                    {{ paper_form.paper }}
                                    <small id="id_paper_error" class="es-error"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer paddingtop-20">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal" style="width: 80px;">Close</button>
                    <input type="submit" class="btn btn-primary btn-sm" value="Submit" style="width: 80px; float: right;">
                </div>
            </form>
        </div>
    </div>
</div>