accounts/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'login/$', 'accounts.views.user_login', name='user_login'),
    url(r'^identify/$', 'accounts.views.user_identify', name='user_identify'),
    url(r'^reset-password/(?P<token>[a-zA-Z0-9]*)/$', 'accounts.views.user_reset_password', name="user_reset_password"),
    url(r'^change-password/$', 'accounts.views.change_password', name='change_password'),
]

editors/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^update-rating/$', 'editors.views.update_editor_rating', name='update_editor_rating'),
    url(r'^create/step1/$', 'editors.views.create_editor_step1', name='create_editor_step1'),
    url(r'^create/step2/$', 'editors.views.create_editor_step2', name='create_editor_step2'),
    url(r'^create-test/$', 'editors.views.create_test', name='create_test'),
    url(r'^test/(?P<test_id>[0-9]+)/$', 'editors.views.start_test', name='start_test'),
    url(r'^skip/(?P<question_id>[0-9]+)/(?P<test_id>[0-9]+)/$', 'editors.views.skip_question', name='skip_question'),
    url(r'^test-completed/(?P<test_id>[0-9]+)/$', 'editors.views.test_completed', name='test_completed'),
    url(r'^create/step3/$', 'editors.views.create_editor_step3', name='create_editor_step3'),
    url(r'^create/step4/$', 'editors.views.create_editor_step4', name='create_editor_step4'),
    url(r'^get-qualification-form/$', 'editors.views.get_qualification_form', name='get_qualification_form'),
    url(r'^get-experience-form/$', 'editors.views.get_experience_form', name='get_experience_form'),
    url(r'^save-qualification-form/$', 'editors.views.save_qualification_form', name='save_qualification_form'),
    url(r'^save-experience-form/$', 'editors.views.save_experience_form', name='save_experience_form'),
    url(r'^edit-qualification-form/(?P<qualification_id>[0-9]+)/$', 'editors.views.edit_qualification_form', name='edit_qualification_form'),
    url(r'^edit-experience-form/(?P<experience_id>[0-9]+)/$', 'editors.views.edit_experience_form', name='edit_experience_form'),
    url(r'^delete-qualification/$', 'editors.views.delete_qualification', name='delete_qualification'),
    url(r'^delete-experience/$', 'editors.views.delete_experience', name='delete_experience'),
    url(r'^show-qualification/$', 'editors.views.show_qualification', name='show_qualification'),
    url(r'^show-experience/$', 'editors.views.show_experience', name='show_experience'),
    url(r'^get-research-interest/$', 'editors.views.get_research_interest', name='get_research_interest'),
    url(r'^quote-request/$', 'editors.views.quote_request', name='quote_request'),
    url(r'^paper-request/$', 'editors.views.paper_request', name='paper_request'),
    url(r'^edit-profile/$', 'editors.views.edit_editor', name='edit_editor'),
    url(r'^delete-file/$', 'editors.views.delete_file', name='delete_file'),
    url(r'^delete-qualification-file/$', 'editors.views.delete_qualification_file', name='delete_qualification_file'),
    url(r'^paper-reject/(?P<paper_id>[0-9]+)/update-status/$', 'editors.views.reject_request', name='reject_request'),
    url(r'^paper/(?P<paper_id>[0-9]+)/update-status/$', 'editors.views.update_paper_status', name='update_paper_status'),
    url(r'^paper/ready/$', 'editors.views.paper_ready', name='paper_ready'),
    url(r'^add-to-cart/$', 'editors.views.add_to_cart', name='add_to_cart'),
    url(r'^raw-paper/download/(?P<paper_id>[0-9]+)/$', 'editors.views.raw_paper_download', name='raw_paper_download'),
    url(r'^paper/download/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_download', name='paper_download'),
    url(r'^paper/approved/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_approved', name='paper_approved'),
    url(r'^paper/complete/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_complete', name='paper_complete'),
    url(r'^rating/$', 'editors.views.rating', name='rating'),
    url(r'^delete-rating/$', 'editors.views.delete_rating', name='delete_rating'),
    url(r'^settings/$', 'editors.views.account_settings', name='settings'),
    url(r'^add-card/$', 'editors.views.add_card', name='add_card'),
    url(r'^make-primary/(?P<payment_method_id>[\w-]+)/$', 'editors.views.make_primary', name='make_primary'),
    url(r'^delete-card/(?P<payment_method_id>[\w-]+)/$', 'editors.views.delete_card', name='delete_card'),
    url(r'^get-paid/$', 'editors.views.get_paid', name='get_paid'),
    url(r'^stripe/connect/$', 'editors.stripe_connect.stripe_connect', name='stripe_connect'),
    url(r'^stripe/authenticated/$', 'editors.stripe_connect.stripe_authenticated', name='stripe_authenticated'),
    url(r'^(?P<username>\w+)/$', 'editors.views.profile', name='profile'),
]

eseditor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home Url
    url(r'^$', 'editors.views.editing_services', name='editing_services'),
    url(r'^about-us/$', 'accounts.views.about_us', name='about_us'),
    url(r'^contact-us/$', 'accounts.views.contact_us', name='contact_us'),
    url(r'^newsletter/$', 'accounts.views.newsletter', name='newsletter'),

    url(r'^editors/$', 'editors.views.editor_home', name='home'),
    url(r'^load_more_editors/$', 'editors.views.load_more_editors', name='load_more_editors'),
    url(r'^load-more-edited-paper/$', 'editors.views.load_more_edited_paper', name='load_more_edited_paper'),
    url(r'^load-more-paper-request/$', 'editors.views.load_more_paper_request', name='load_more_paper_request'),
    url(r'^load-more-quotes-request/$', 'editors.views.load_more_quotes_request', name='load_more_quotes_request'),
    url(r'^load-more-fiancial-activites/$', 'editors.views.load_more_fiancial_activities', name='load_more_fiancial_activities'),
    url(r'^job-page/paper/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_detail', name='paper_detail'),

    # App Url
    url(r'editors/', include('editors.urls')),
    url(r'student/', include('students.urls')),
    url(r'accounts/', include('accounts.urls')),
    url(r'messages/', include('message.urls')),

    # Logout Url
    url(r'^logout/$', views.logout, {'next_page': settings.LOGIN_URL}, name="logout"),

    # Reset Password Url
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
         name='password_reset_done'),

    # Rating URLs
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),

    # checkout Url
    url(r'^checkout/$', 'editors.views.checkout', name='checkout'),

    # Media Url
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT})
]

accounts/models.py
from django.db import models


class PasswordResetAuth(models.Model):
    email = models.EmailField(max_length=75)
    token = models.CharField(max_length=11)
    is_expired = models.BooleanField(default=False)

    def __str__(self):
        return u'%s' % self.email


class Newsletter(models.Model):
    email = models.EmailField(max_length=75)

    def __str__(self):
        return u'%s' % self.email

accounts/forms.py
from __future__ import unicode_literals

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from django.contrib.auth.forms import PasswordResetForm

from accounts.models import PasswordResetAuth


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=75, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get("email", "")

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Account doesn't exist with this email id. Please try again!")
        else:
            user = User.objects.get(email=email)
            cleaned_data["username"] = user.username

        return cleaned_data


class PasswordChangeForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

    def clean_old_password(self):
        """
        Validates that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]

        if not self.user.check_password(old_password):
            raise forms.ValidationError("Your old password was entered incorrectly. Please enter it again.")

        return old_password

    def clean_confirm_password(self):
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if new_password and confirm_password:
            if new_password != confirm_password:
                raise forms.ValidationError("The two password fields didn't match.")

        password_validation.validate_password(confirm_password, self.user)

        return confirm_password

    def save(self, commit=True):
        password = self.cleaned_data["new_password"]
        self.user.set_password(password)

        if commit:
            self.user.save()

        return self.user


class IdentifyForm(forms.Form):
    email = forms.EmailField(max_length=75, widget=forms.TextInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        cleaned_data = super(IdentifyForm, self).clean()
        email = cleaned_data.get("email", "")
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError("Account doesn't exist with this email id. Please try again!")
        return email


class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        self.token = kwargs.pop('token', None)
        super(ResetPasswordForm, self).__init__(*args, **kwargs)

    def clean_confirm_password(self):
        cleaned_data = super(ResetPasswordForm, self).clean()
        new_password = cleaned_data.get("new_password", "")
        confirm_password = cleaned_data.get("confirm_password", "")

        if new_password != confirm_password:
            raise forms.ValidationError("Password did not match. Make it correct.")

        if not PasswordResetAuth.objects.filter(token=self.token, is_expired=False).exists():
            raise forms.ValidationError("Either you are not an identified user or token has been expired. So please click on forget password.")

        return confirm_password


class ContactForm(forms.Form):
    email = forms.EmailField(max_length=75, widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'cols': '0', 'rows': '8'}))

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block top %}
    <section class="breadcrumb-classic context-dark">
        <div class="shell section-30 section-sm-top-10 section-sm-bottom-10">
            <h2 class="veil reveal-sm-block text-center">Change Password</h2>
        </div>
    </section>
{% endblock %}
{% block content %}
<style type="text/css">
        
        .error {
            display: none!important;
        }
    </style>

    <main class="page-content section-70 section-md-114">
        <section class="section-98 section-sm-110 section-bottom-66">
            <div class="shell">
                <div class="range range-xs-center section-34">
                    <div class="cell-xs-8 cell-sm-6 cell-md-6">
                        <div class="row">
                            <div class="col-md-12">
                                <h5>Change Password</h5>
                                <div class="text-subline"></div>
                            </div>
                        </div>
                        <form class="form-horizontal" id="chng_pass" method="post" data-toggle="validator" style="color: black; margin-top: 20px;">
                            {% csrf_token %}
                            <div class="form-group {% if form.old_password.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="id_old_password" class="control-label">Old Password:</label>
                                    {{ form.old_password }}
                                    <small><div class="help-block with-errors"></div></small>
                                    <small class="es-error">{{ form.old_password.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="form-group {% if form.new_password.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="id_new_password" class="control-label">New Password:</label>
                                    {{ form.new_password }}
                                    <small><div class="help-block with-errors"></div></small>
                                    <small class="es-error">{{ form.new_password.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="form-group {% if form.confirm_password.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="id_confirm_password" class="control-label">Confirm Password:</label>
                                    {{ form.confirm_password }}
                                    <small><div class="help-block with-errors"></div></small>
                                    <small class="es-error">{{ form.confirm_password.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <input class="btn btn-primary btn-md" type="submit" value="Change Password"/ style="width: 180px;">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <br>

{% endblock %}

{% block javascript %}

<script src ="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript">

    $(document).ready(function() {

        $('#chng_pass').validate({
            rules: {
                
                old_password: {
                    required: true,
                    minlength: 8,
                },

                new_password:{
                    required: true,
                    minlength: 8,

                },
                confirm_password:{
                    required: true,
                    minlength: 8, 
                }
                
            },
            
            highlight: function(element) {

                $(element).closest('.form-group').addClass('has-error');
                $(element).closest('.form-group').find('.es-error').text("This field is required.").show();
               
            },
            success: function(element) {

                $(element).closest('.form-group').removeClass('has-error');
                $(element).closest('.form-group').find('.es-error').hide();

            },
            submitHandler: function(form) {
                form.submit()
            }

        });
    });
</script>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block top %}
    <section class="breadcrumb-classic context-dark">
        <div class="shell section-30 section-sm-top-10 section-sm-bottom-10">
            <h2 class="veil reveal-sm-block text-center">Login</h2>
        </div>
    </section>
{% endblock %}            

{% block content %}
    <style type="text/css">
        .error {
            display: none!important;
        }
    </style>

    <main class="page-content section-70 section-md-114">
        <section class="section-98 section-sm-110 section-bottom-66">
            <div class="shell">
                <div class="range range-xs-center section-34">
                    <div class="cell-xs-8 cell-sm-6 cell-md-6">
                        <!-- <h2 class="text-bold text-center">Sign In</h2>
                        <hr class="divider bg-madison"> -->
                        <div class="row">
                            <div class="col-md-12">
                                <h5>Sign In</h5>
                                <div class="text-subline"></div>
                            </div>
                        </div>
                        <form id="login_form" class="form-horizontal" method="post" style="color: black; margin-top: 20px;">
                            {% csrf_token %}
                            {% if form.non_field_errors and not form.email.errors %}
                                <small class="es-error">{{ form.non_field_errors.as_text }}</small>
                            {% elif error_message %}
                                <small class="es-error">{{ error_message }}</small>
                            {% endif %}
                            <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="id_email" class="control-label"><h5><strong>Email:</strong></h5></label>
                                    {{ form.email }}
                                    <small><div class="help-block with-errors"></div></small>
                                    <small class="es-error">{{ form.email.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="form-group {% if form.password.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="id_password" class="control-label"><h5><strong>Password:</strong></h5></label>
                                    {{ form.password }}
                                    <small><div class="help-block with-errors"></div></small>
                                    <small class="es-error">{{ form.password.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="clearfix">
                                        <input class="btn btn-primary btn-md" type="submit" value="Login"/>
                                        <div class="pull-right" style="margin-top: 20px;">
                                            <a href="{% url 'user_identify' %}" ><strong>Forget Password?</strong></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <br>

{% endblock %}


{% block javascript %}

<script src ="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript">

    $(document).ready(function() {

        $('#login_form').validate({
            rules: {
                email: {
                    required: true
                },

                password:{
                    required: true
                }                
            },
            highlight: function(element) {

                $(element).closest('.form-group').addClass('has-error');
                $(element).closest('.form-group').find('.es-error').text("This field is required.").show();
               
            },
            success: function(element) {

                $(element).closest('.form-group').removeClass('has-error');
                $(element).closest('.form-group').find('.es-error').hide();

            },
            submitHandler: function(form) {
                form.submit()
            }

        });
    });    
</script>
{% endblock %}

templates/accounts/user_identify.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Reset Password{% endblock %}

{% block top %}
    <section class="breadcrumb-classic context-dark">
        <div class="shell section-30 section-sm-top-10 section-sm-bottom-10">
            <h2 class="veil reveal-sm-block text-center">Reset Password</h2>
        </div>
    </section>
{% endblock %}

{% block content%}
<style type="text/css">
       
        .error {
            display: none!important;
        }
    </style>

    <main class="page-content section-70 section-md-114">
        <section class="section-98 section-sm-110 section-bottom-66">
            <div class="shell">
                <div class="range range-xs-center section-34">
                    <div class="cell-xs-8 cell-sm-6 cell-md-6">
                        <div class="row">
                            <div class="col-md-12">
                                <h5>Forgot Password</h5>
                                <div class="text-subline"></div>
                            </div>
                        </div>
                        <form class="form-horizontal" id="user_iden" method="post" style="color: black; margin-top: 20px;">
                            {% csrf_token %}
                            <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="id_email" class="control-label"><h5><strong>Email</strong></h5></label>
                                    <input id="id_email" type="text" class="form-control" name="email" placeholder="Email" aria-describedby="basic-addon1">
                                    <small><div class="help-block with-errors"></div></small>
                                    <small class="es-error">{{ form.email.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="clearfix">
                                        <input class="btn btn-primary btn-md" type="submit" value="Reset Password"/>
                                        <div class="pull-right" style="margin-top: 20px;">
                                            <a href="{% url 'user_login' %}"><strong>Login</strong></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <br>
{% endblock %}

{% block javascript %}
    
    <script src ="{% static 'js/jquery.validate.min.js' %}"></script>

    <script type="text/javascript">
        
        $(document).ready(function() {

            $('#user_iden').validate({
                rules: {
                    email: {
                        required: true
                    },
                    
                },
                highlight: function(element) {

                    $(element).closest('.form-group').addClass('has-error');
                    $(element).closest('.form-group').find('.es-error').text("This field is required.").show();
                   
                },
                success: function(element) {

                    $(element).closest('.form-group').removeClass('has-error');
                    $(element).closest('.form-group').find('.es-error').hide();

                },
                submitHandler: function(form) {
                    form.submit()
                }

            });
        });    
    </script>
{% endblock %}

templates/accounts/user_reset_password.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}
{% load staticfiles %}

{% block top %}
    <section class="breadcrumb-classic context-dark">
        <div class="shell section-30 section-sm-top-10 section-sm-bottom-10">
            <h2 class="veil reveal-sm-block text-center">Reset Password</h2>
        </div>
    </section>
{% endblock %}

{% block content %}
    <style type="text/css">
        .error {
            display: none!important;
        }
    </style>

    <main class="page-content section-70 section-md-114">
        <section class="section-98 section-sm-110 section-bottom-66">
            <div class="shell">
                <div class="range range-xs-center section-34">
                    <div class="cell-xs-8 cell-sm-6 cell-md-6">
                        <div class="row">
                            <div class="col-md-12">
                                <h5>Reset Password</h5>
                                <div class="text-subline"></div>
                            </div>
                        </div>
                        <form id="res_pass" class="form-horizontal" method="post" style="color: black; margin-top: 20px;">
                            {% csrf_token %}
                            
                            <div class="form-group {% if form.new_password.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="id_new_password" class="control-label"><h5><strong>New Password:</strong></h5></label>
                                    {{ form.new_password }}
                                    <small><div class="help-block with-errors"></div></small>
                                    <small class="es-error">{{ form.new_password.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="form-group {% if form.confirm_password.errors %}has-error{% endif %}">
                                <div class="col-md-12">
                                    <label for="id_confirm_password" class="control-label"><h5><strong>Confirm Password:</strong></h5></label>
                                    {{ form.confirm_password }}
                                    <small><div class="help-block with-errors"></div></small>
                                    <small class="es-error">{{ form.confirm_password.errors.as_text }}</small>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="clearfix">
                                        <div>
                                            <input class="btn btn-primary btn-md" type="submit" value="Reset Password"/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <br>
    
   
{% endblock %}

{% block javascript %}

<script src ="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript">

    $(document).ready(function() {

        $('#res_pass').validate({
            rules: {
                new_password: {
                    required: true
                },

                confirm_password:{
                    required: true
                }                
            },
            highlight: function(element) {

                $(element).closest('.form-group').addClass('has-error');
                $(element).closest('.form-group').find('.es-error').text("This field is required.").show();
               
            },
            success: function(element) {

                $(element).closest('.form-group').removeClass('has-error');
                $(element).closest('.form-group').find('.es-error').hide();

            },
            submitHandler: function(form) {
                form.submit()
            }

        });
    });    
</script>
{% endblock %}