editors/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^update-rating/$', 'editors.views.update_editor_rating', name='update_editor_rating'),
    url(r'^create/step1/$', 'editors.views.create_editor_step1', name='create_editor_step1'),
    url(r'^create/step2/$', 'editors.views.create_editor_step2', name='create_editor_step2'),
    url(r'^create-test/$', 'editors.views.create_test', name='create_test'),
    url(r'^test/(?P<test_id>[0-9]+)/$', 'editors.views.start_test', name='start_test'),
    url(r'^skip/(?P<question_id>[0-9]+)/(?P<test_id>[0-9]+)/$', 'editors.views.skip_question', name='skip_question'),
    url(r'^test-completed/(?P<test_id>[0-9]+)/$', 'editors.views.test_completed', name='test_completed'),
    url(r'^create/step3/$', 'editors.views.create_editor_step3', name='create_editor_step3'),
    url(r'^create/step4/$', 'editors.views.create_editor_step4', name='create_editor_step4'),
    url(r'^get-qualification-form/$', 'editors.views.get_qualification_form', name='get_qualification_form'),
    url(r'^get-experience-form/$', 'editors.views.get_experience_form', name='get_experience_form'),
    url(r'^save-qualification-form/$', 'editors.views.save_qualification_form', name='save_qualification_form'),
    url(r'^save-experience-form/$', 'editors.views.save_experience_form', name='save_experience_form'),
    url(r'^edit-qualification-form/(?P<qualification_id>[0-9]+)/$', 'editors.views.edit_qualification_form', name='edit_qualification_form'),
    url(r'^edit-experience-form/(?P<experience_id>[0-9]+)/$', 'editors.views.edit_experience_form', name='edit_experience_form'),
    url(r'^delete-qualification/$', 'editors.views.delete_qualification', name='delete_qualification'),
    url(r'^delete-experience/$', 'editors.views.delete_experience', name='delete_experience'),
    url(r'^show-qualification/$', 'editors.views.show_qualification', name='show_qualification'),
    url(r'^show-experience/$', 'editors.views.show_experience', name='show_experience'),
    url(r'^get-research-interest/$', 'editors.views.get_research_interest', name='get_research_interest'),
    url(r'^quote-request/$', 'editors.views.quote_request', name='quote_request'),
    url(r'^paper-request/$', 'editors.views.paper_request', name='paper_request'),
    url(r'^edit-profile/$', 'editors.views.edit_editor', name='edit_editor'),
    url(r'^delete-file/$', 'editors.views.delete_file', name='delete_file'),
    url(r'^delete-qualification-file/$', 'editors.views.delete_qualification_file', name='delete_qualification_file'),
    url(r'^paper-reject/(?P<paper_id>[0-9]+)/update-status/$', 'editors.views.reject_request', name='reject_request'),
    url(r'^paper/(?P<paper_id>[0-9]+)/update-status/$', 'editors.views.update_paper_status', name='update_paper_status'),
    url(r'^paper/ready/$', 'editors.views.paper_ready', name='paper_ready'),
    url(r'^add-to-cart/$', 'editors.views.add_to_cart', name='add_to_cart'),
    url(r'^raw-paper/download/(?P<paper_id>[0-9]+)/$', 'editors.views.raw_paper_download', name='raw_paper_download'),
    url(r'^paper/download/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_download', name='paper_download'),
    url(r'^paper/approved/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_approved', name='paper_approved'),
    url(r'^paper/complete/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_complete', name='paper_complete'),
    url(r'^rating/$', 'editors.views.rating', name='rating'),
    url(r'^delete-rating/$', 'editors.views.delete_rating', name='delete_rating'),
    url(r'^settings/$', 'editors.views.account_settings', name='settings'),
    url(r'^add-card/$', 'editors.views.add_card', name='add_card'),
    url(r'^make-primary/(?P<payment_method_id>[\w-]+)/$', 'editors.views.make_primary', name='make_primary'),
    url(r'^delete-card/(?P<payment_method_id>[\w-]+)/$', 'editors.views.delete_card', name='delete_card'),
    url(r'^get-paid/$', 'editors.views.get_paid', name='get_paid'),
    url(r'^stripe/connect/$', 'editors.stripe_connect.stripe_connect', name='stripe_connect'),
    url(r'^stripe/authenticated/$', 'editors.stripe_connect.stripe_authenticated', name='stripe_authenticated'),
    url(r'^(?P<username>\w+)/$', 'editors.views.profile', name='profile'),
]

eseditor/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    # Home Url
    url(r'^$', 'editors.views.editing_services', name='editing_services'),
    url(r'^about-us/$', 'accounts.views.about_us', name='about_us'),
    url(r'^contact-us/$', 'accounts.views.contact_us', name='contact_us'),
    url(r'^newsletter/$', 'accounts.views.newsletter', name='newsletter'),

    url(r'^editors/$', 'editors.views.editor_home', name='home'),
    url(r'^load_more_editors/$', 'editors.views.load_more_editors', name='load_more_editors'),
    url(r'^load-more-edited-paper/$', 'editors.views.load_more_edited_paper', name='load_more_edited_paper'),
    url(r'^load-more-paper-request/$', 'editors.views.load_more_paper_request', name='load_more_paper_request'),
    url(r'^load-more-quotes-request/$', 'editors.views.load_more_quotes_request', name='load_more_quotes_request'),
    url(r'^load-more-fiancial-activites/$', 'editors.views.load_more_fiancial_activities', name='load_more_fiancial_activities'),
    url(r'^job-page/paper/(?P<paper_id>[0-9]+)/$', 'editors.views.paper_detail', name='paper_detail'),

    # App Url
    url(r'editors/', include('editors.urls')),
    url(r'student/', include('students.urls')),
    url(r'accounts/', include('accounts.urls')),
    url(r'messages/', include('message.urls')),

    # Logout Url
    url(r'^logout/$', views.logout, {'next_page': settings.LOGIN_URL}, name="logout"),

    # Reset Password Url
    url(r'^user/password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
         name='password_reset_done'),

    # Rating URLs
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),

    # checkout Url
    url(r'^checkout/$', 'editors.views.checkout', name='checkout'),

    # Media Url
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT})
]

message/urls.py
from django.conf.urls import url


urlpatterns = [
    url(r'^$', 'message.views.message', name='message'),
    url(r'^details/(?P<msg_id>[0-9]+)/$', 'message.views.message_details', name='message_details'),

]    

editors/models.py
from __future__ import unicode_literals

import os
import stripe
from datetime import datetime

from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django_countries.fields import CountryField
from django.core.files.storage import FileSystemStorage
from autoslug import AutoSlugField
from star_ratings.models import Rating

from editors.utils import get_year_drop_down, get_service_fee
from editors.encryption import decrypt_aes
from students.models import Students
from editors import FINANCIAL_CHOICES
from solo.models import SingletonModel

media_storage = FileSystemStorage(location=settings.BASE_DIR, base_url="/media/")

stripe.api_key = settings.STRIPE_SECRET_KEY

YEAR_DROP_DOWN = get_year_drop_down()

MONTH_CHOICES = (
    ('january', 'January'),
    ('february', 'February'),
    ('march', 'March'),
    ('april', 'April'),
    ('may', 'May'),
    ('june', 'June'),
    ('july', 'July'),
    ('august', 'August'),
    ('september', 'September'),
    ('october', 'October'),
    ('november', 'November'),
    ('december', 'December'),
)

RESEARCH_METHOD_CHOICES = (
    ('Quantitative', 'Quantitative'),
    ('Qualitative', 'Qualitative'),
    ('Both', 'Both'),
    ('Others', 'Others'),
)

DEGREE_LEVEL_CHOICES = (
    ('Bachelor', 'Bachelor'),
    ('Masters', 'Masters'),
    ('PhD', 'PhD'),
)

PAPER_STATUS_CHOICES = (
    ('Draft', 'Draft'),
    ('Rejected', 'Rejected'),
    ('Pending', 'Pending'),
    ('Progress', 'Progress'),
    ('Ready To Review', 'Ready To Review'),
    ('Approved', 'Approved'),
    ('Completed', 'Completed'),
)

REFERENCING_CHOICES = (
    ('Harvard', 'Harvard'),
    ('Oxford', 'Oxford'),
    ('Chicago', 'Chicago'),
    ('APA', 'APA'),
    ('MLA', 'MLA'),
    ('Others', 'Others'),
)

DIFFICULTY_LEVEL = (
    ('EASY', 'EASY'),
    ('MEDIUM', 'MEDIUM'),
    ('DIFFICULT', 'DIFFICULT'),
)

EXP_YEAR = [(x, x) for x in range(datetime.today().date().year, datetime.today().date().year + 15)]

EXP_MONTH = [
    ('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'),
    ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December'),
]


class ResearchInterest(models.Model):
    slug = AutoSlugField(populate_from='interest', unique=True)
    interest = models.CharField(max_length=40)

    def __str__(self):
        return u'%s' %(self.interest)


class Discipline(models.Model):
    slug = AutoSlugField(populate_from='name', unique=True)
    name = models.CharField(max_length=40)

    def __str__(self):
        return u'%s' %(self.name)


class Editors(models.Model):
    user = models.ForeignKey(User)
    avatar = models.ImageField(upload_to="profile/editors/", null=True, blank=True)
    phone_no = models.CharField(max_length=15, blank=True, null=True)
    street1 = models.CharField(max_length=60, blank=True, null=True)
    street2 = models.CharField(max_length=60, blank=True, null=True)
    city  = models.CharField(max_length=30, blank=True, null=True)
    state = models.CharField(max_length=30, blank=True, null=True)
    postal_code = models.CharField(max_length=12, blank=True, null=True)
    nationality = models.CharField(max_length=255, blank=True, null=True)
    bio = models.TextField(null=True, blank=True)
    research_methods = models.CharField(max_length=60, null=True, blank=True, choices=RESEARCH_METHOD_CHOICES)
    referencing_style = models.CharField(max_length=60, null=True, blank=True, choices=REFERENCING_CHOICES)
    optional_research_methods = models.CharField(max_length=60, null=True, blank=True)
    optional_referencing_style = models.CharField(max_length=60, null=True, blank=True)
    discipline = models.ManyToManyField(Discipline)
    research_interest = models.ManyToManyField(ResearchInterest)
    identity_document = models.FileField(upload_to="documents/identity/", null=True, blank=True)
    address_document = models.FileField(upload_to="documents/address/", null=True, blank=True)
    qualification_document = models.FileField(upload_to="documents/qualification/", null=True, blank=True)
    country = CountryField(blank_label="(select country)", null=True, blank=True)
    rating_star = models.FloatField(default=0.0)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return u'%s %s' %(self.user.first_name, self.user.last_name)

    def get_identity_document(self):
        return os.path.basename(self.identity_document.name)

    def get_address_document(self):
        return os.path.basename(self.address_document.name)

    def get_qualification_document(self):
        return os.path.basename(self.qualification_document.name)

    def get_total_balance(self):
        total = 0
        for activity in self.editor.all():
            if activity.type == "Credit":
                total += activity.amount
            else:
                total -= activity.amount
        return total


class ProfileViewer(models.Model):
    editor = models.ForeignKey(Editors)
    user = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    difficulty_level = models.CharField(max_length=60, null=True, blank=True, choices=DIFFICULTY_LEVEL)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.question_text


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.answer_text


class Test(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    editor = models.ForeignKey(Editors)
    finished = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    title = models.CharField(max_length=255, null=True, blank=True)
    score = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return '%s for %s' % (self.title, self.editor.user.get_full_name())


class TestQuestion(models.Model):
    question = models.ForeignKey(Question, related_name="question")
    answer = models.ForeignKey(Answer, related_name="answer", null=True, blank=True)
    test = models.ForeignKey(Test, related_name="test")
    is_attempted = models.BooleanField(default=False)

    def __str__(self):
        return '%s - %s' % (self.question.question_text, self.test.title)


class Qualification(models.Model):
    editor = models.ForeignKey(Editors)
    degree = models.CharField(max_length=30, blank=True, null=True)
    university = models.CharField(max_length=30, blank=True, null=True)
    from_month = models.CharField(max_length=20, null=True, blank=True, choices=MONTH_CHOICES)
    from_year = models.CharField(max_length=4, null=True, blank=True, choices=YEAR_DROP_DOWN)
    to_month = models.CharField(max_length=20, null=True, blank=True, choices=MONTH_CHOICES)
    to_year = models.CharField(max_length=4, null=True, blank=True, choices=YEAR_DROP_DOWN)
    degree_level = models.CharField(max_length=20, null=True, blank=True, choices=DEGREE_LEVEL_CHOICES)
    qualification_document = models.FileField(upload_to="documents/qualification/", null=True, blank=True)

    def __str__(self):
        return u'%s' %(self.editor)

    def get_from_month(self):
        return dict(MONTH_CHOICES).get(self.from_month)

    def get_to_month(self):
        return dict(MONTH_CHOICES).get(self.to_month)


class Experience(models.Model):
    editor = models.ForeignKey(Editors)
    company_name = models.CharField(max_length=32)
    title = models.CharField(max_length=70, null=True, blank=True)
    location = models.CharField(max_length= 50, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    is_current = models.BooleanField(default=False)
    from_month = models.CharField(max_length=20, null=True, blank=True, choices=MONTH_CHOICES)
    from_year = models.CharField(max_length=4, null=True, blank=True, choices=YEAR_DROP_DOWN)
    to_month = models.CharField(max_length=20, null=True, blank=True, choices=MONTH_CHOICES)
    to_year = models.CharField(max_length=4, null=True, blank=True, choices=YEAR_DROP_DOWN)

    def __str__(self):
        return u'%s' %(self.company_name)

    def get_from_month(self):
        return dict(MONTH_CHOICES).get(self.from_month)

    def get_to_month(self):
        return dict(MONTH_CHOICES).get(self.to_month)


class Quotation(models.Model):
    editor = models.ForeignKey(Editors)
    discipline = models.ForeignKey(Discipline, null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    words_count = models.CharField(max_length=255)
    document = models.FileField(upload_to="papers/quotation-documents/", null=True, blank=True)
    student = models.ForeignKey(Students, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        return u'%s requested quotes from %s' % (self.student, self.editor)


class PaperRequest(models.Model):
    editor = models.ForeignKey(Editors)
    discipline = models.ForeignKey(Discipline, null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    words_count = models.CharField(max_length=255)
    price = models.FloatField(null=True, blank=True)
    price_paid = models.FloatField(null=True, blank=True)
    raw_paper = models.FileField(upload_to="papers/raw/")
    status = models.CharField(max_length=60, choices=PAPER_STATUS_CHOICES, default='Draft')

message/forms.py
from __future__ import unicode_literals

from django import forms
from django.conf import settings
from django.contrib.auth.models import User

from message.models import Message

class MessageForm(forms.ModelForm):
    
    fields = ['sender', 'recipient', 'parent_msg', 'subject', 'message']

    class Meta:
        model=Message
        exclude = ['sender_read', 'recipient_read', 'created']
        widgets = {
            'sender': forms.HiddenInput(),
            'recipient': forms.HiddenInput(),
            'parent_msg': forms.HiddenInput(),
            'subject': forms.HiddenInput(),
        }

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({'class': 'form-control', 'cols': '0', 'rows': '4'})
        self.fields["message"].required = True

templates/message/details.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-tagsinput.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-tagsinput-typeahead.css' %}">
    <script src="{% static 'js/bloodhound.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap-typeahead.js' %}"></script>
    <script src="{% static 'js/bootstrap-tagsinput.js' %}"></script>
    <script src="{% static 'js/jquery.jtruncate.js' %}"></script>
    <script src ="{% static 'js/jquery.validate.min.js' %}"></script>

    <script type="text/javascript">
        $('#reply_form').validate({
            ignore: "",
            rules: {
                message: {
                    
                    required: true
                },
            },
            highlight: function(element) {

                $(element).closest('.form-group').addClass('has-error');
                $(element).closest('.form-group').find('.es-error').text("This field is required.").show();
               
            },
            success: function(element) {

                $(element).closest('.form-group').removeClass('has-error');
                $(element).closest('.form-group').find('.es-error').hide();

            },
            submitHandler: function(form) {
                form.submit()
            }

        });
    </script>
{% endblock %}
{% block top %}
    <section class="breadcrumb-classic context-dark">
        <div class="shell section-30 section-sm-top-10 section-sm-bottom-10">
            <h2 class="veil reveal-sm-block text-center">Conversations</h2>
        </div>
    </section>
{% endblock %} 

{% block content %}
<style type="text/css">
    .error {
        display: none!important;
    }
</style>
    {% if role == 'student' %}
        <div class="row">
            <div class="hidden-xs pull-right" style="margin-top: 20px; margin-right: 14px;">
                {% if not msg_obj.paper_request %}
                    <button type="button" class="btn btn-primary" onclick="openmodal('{{ msg_obj.recipient.editors_set.all.0.id }}')">Submit Paper</button>
                {% endif %}
            </div>
            <div class="col-xs-6 pull-right visible-xs" style="margin-top: 6px;">
                {% if not msg_obj.paper_request %}
                    <button type="button" class="btn btn-primary" onclick="openmodal('{{ msg_obj.recipient.editors_set.all.0.id }}')">Submit Paper</button>
                {% endif %}    
            </div>
        </div> 
    {% endif %}
  
    <div class="col-md-12" style="margin-top: 10px; margin-bottom: 20px;">
        <div class="row">
            <div class="profile-block" style="color: black;">
                <div class="row">
                    <div class="col-md-2 col-md-offset-0 col-xs-4 col-xs-offset-4">
                        <div class="circle">
                            {% with msg_obj.sender as sender %}
                                <div class="thubmnail-inner img-rounded" style="height: 70px;">
                                    {% if sender.students_set.all %}
                                        <img class="img-circle" src="{% if sender.students_set.all.0.avatar %}{{ sender.students_set.all.0.avatar.url }}{% else %}{% static 'images/nodp.jpg' %}{% endif %}" width="70" height="70">
                                    {% else %}
                                        <a href="/editors/{{ sender.editors_set.all.0.user.username }}/" class="thubmnail-inner img-rounded" style="height: 70px;">
                                            <img class="img-circle" src="{% if sender.editors_set.all.0.avatar %}{{ sender.editors_set.all.0.avatar.url }}{% else %}{% static 'images/nodp.jpg' %}{% endif %}" width="70" height="70">
                                        </a>
                                    {% endif %}
                                </div>
                                <div>
                                    <span class="tag label label-info"><strong>{{ msg_obj.sender.get_full_name }}</strong></span>
                                </div>
                            {% endwith %}
                        </div>
                    </div>
                    <div class="col-md-8 col-xs-12" style="margin-bottom: 20px;">
                        <div class="message_truncate" style="text-align: justify-all;">{{ msg_obj.message|safe }}</div>
                    </div>
                    <div class="col-md-2 col-xs-12">
                        <strong>{{ msg_obj.created|date:"M d, Y" }}</strong>
                        <small class="text-muted text-center">{{ msg_obj.created|time:"g:iA"|lower }}</small>
                    </div>
                </div>    
            </div>
        </div>
        <div class="row paddingtop-20">
            {% for message in child_msg %}
                <div class="profile-block" style="color: black">
                    <div class="row">
                        <div class="col-md-2 col-md-offset-0 col-xs-4 col-xs-offset-4">
                            <div class="circle">
                                {% with message.sender as sender %}
                                    <div class="thubmnail-inner img-rounded" style="height: 70px">
                                        {% if sender.students_set.all %}
                                            <img class="img-circle" src="{% if sender.students_set.all.0.avatar %}{{ sender.students_set.all.0.avatar.url }}{% else %}{% static 'images/nodp.jpg' %}{% endif %}" width="70" height="70">
                                        {% else %}
                                            <a href="/editors/{{ sender.editors_set.all.0.user.username }}/" class="thubmnail-inner img-rounded" style="height: 70px;">
                                                <img class="img-circle" src="{% if sender.editors_set.all.0.avatar %}{{ sender.editors_set.all.0.avatar.url }}{% else %}{% static 'images/nodp.jpg' %}{% endif %}" width="70" height="70">
                                            </a>
                                        {% endif %}
                                    </div>
                                    <div>
                                        {% if sender.students_set.all %}
                                            <span class="tag label label-info"><strong>{{ message.sender.get_full_name }}</strong></span>
                                        {% else %}
                                            <a href="/editors/{{ sender.editors_set.all.0.user.username }}/"><span class="tag label label-success"><strong>{{ message.sender.get_full_name }}</strong></span></a>  
                                        {% endif %}
                                    </div>
                                {% endwith %}
                            </div>
                        </div>
                        <div class="col-md-8 col-xs-12" style="margin-bottom: 20px;">
                            <div class="" style="text-align: justify;">{{ message.message|safe }}</div>
                        </div>
                        <div class="col-md-2 col-xs-12">
                            <strong>{{ message.created|date:"M d, Y" }}</strong>
                            <small class="text-muted text-center">{{ message.created|time:"g:iA"|lower }}</small>
                        </div>
                    </div>    
                </div>
            {% endfor %}
        </div>
        <div class="row" style="margin-top: 10px;">
            <form id="reply_form" role="form" method="post">
                {% csrf_token %}
                {{ form.sender }}
                {{ form.recipient }}
                {{ form.parent_msg }}
                {{ form.subject }}
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            {{ form.message }}
                            <small class="es-error">{{ form.message.errors.as_text }}</small>
                            <div class="help-block with-errors"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-xs-3" style="margin-top: 5px;">
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" value="Send"/ style="width: 120px;">
                        </div> 
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="modal fade" id="id_request_quote_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-overlay" id="id_quote_overlay">
                    <img src="{% static 'images/spin.svg' %}"/>
                </div>
                <form id="id_request_quote_form" class="form-horizontal" action="{% url 'quote_request' %}" enctype="multipart/form-data" method="post" onsubmit="return quote_request($(this))" style="color: black;">
                    {% csrf_token %}
                    {{ quote_form.editor_id }}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Submit Document</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row paddingtop-20">
                            <div class="col-md-12">
                                <div class="form-group" id="id_document_error_parent_div">
                                    <label for="document" class="control-label col-md-2" style="margin-top: -15px;">Document</label>
                                    <div class="col-md-10">
                                        {{ quote_form.document }}
                                        <small id="id_document_error" class="es-error"></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer paddingtop-20">
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal" style="width: 80px;">Close</button>
                        <input type="submit" class="btn btn-primary btn-sm" value="Submit" style="width: 80px; float: right;">
                    </div>
                </form>
            </div>
      </div>
      </div>
    </div>

{% endblock %}